services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: mydb

  todoapp-container-backend:
    image: todoapp-backend
    ports: 
    - 8000:8000
    environment:
      SECRET_KEY: django-insecure-2ykcprawj#=-$w+r$$oncm6m*=v35)+&2zn$0l@t2ueka^qsqp
      DATABASE_URL: postgres://admin:qwerty@db:5432/mydb

  todoapp-container-frontend:
    image: todoapp-frontend
    ports:
    - 5173:5173
    environment:
      VITE_API_URL_LOCAL: http://127.0.0.1:8000/
